# 01 - Data Collection and Understanding

In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/air_quality_raw.csv")
print(df.shape)

(3314, 11)

In [2]:
df.head(10)

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Andhra_Pradesh,Amaravati,"Secretariat, Amaravati - APPCB",30-01-2024 10:00:00,16.515083,80.518167,CO,17.0,70.0,51.0
1,India,Andhra_Pradesh,Anantapur,"Gulzarpet, Anantapur - APPCB",30-01-2024 10:00:00,14.675886,77.593027,PM10,45.0,109.0,70.0
2,India,Andhra_Pradesh,Anantapur,"Gulzarpet, Anantapur - APPCB",30-01-2024 10:00:00,14.675886,77.593027,OZONE,2.0,59.0,26.0
3,India,Andhra_Pradesh,Chittoor,"Gangineni Cheruvu, Chittoor - APPCB",30-01-2024 10:00:00,13.204880,79.097889,NO2,9.0,28.0,14.0
4,India,Andhra_Pradesh,Chittoor,"Gangineni Cheruvu, Chittoor - APPCB",30-01-2024 10:00:00,13.204880,79.097889,SO2,5.0,24.0,10.0
5,India,Andhra_Pradesh,Chittoor,"Gangineni Cheruvu, Chittoor - APPCB",30-01-2024 10:00:00,13.204880,79.097889,OZONE,8.0,116.0,24.0
6,India,Andhra_Pradesh,Kadapa,"Yerramukkapalli, Kadapa - APPCB",30-01-2024 10:00:00,14.465052,78.824187,PM2.5,24.0,51.0,44.0
7,India,Andhra_Pradesh,Kadapa,"Yerramukkapalli, Kadapa - APPCB",30-01-2024 10:00:00,14.465052,78.824187,PM10,22.0,43.0,37.0
8,India,Andhra_Pradesh,Kadapa,"Yerramukkapalli, Kadapa - APPCB",30-01-2024 10:00:00,14.465052,78.824187,OZONE,21.0,56.0,32.0
9,India,Andhra_Pradesh,Rajamahendravaram,"Anand Kala Kshetram, Rajamahendravaram - APPCB",30-01-2024 10:00:00,16.987287,81.736318,NH3,4.0,7.0,5.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3314 entries, 0 to 3313
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        3314 non-null   object
 1   state          3314 non-null   object
 2   city           3314 non-null   object
 3   station        3314 non-null   object
 4   last_update    3314 non-null   object
 5   latitude       3314 non-null   float64
 6   longitude      3314 non-null   float64
 7   pollutant_id   3314 non-null   object
 8   pollutant_min  3093 non-null   float64
 9   pollutant_max  3093 non-null   float64
 10  pollutant_avg  3093 non-null   float64
dtypes: float64(5), object(6)
memory usage: 284.9+ KB

In [4]:
df.isnull().sum()

country            0
state              0
city               0
station            0
last_update        0
latitude           0
longitude          0
pollutant_id       0
pollutant_min    221
pollutant_max    221
pollutant_avg    221
dtype: int64

In [5]:
print("States  :", df["state"].nunique())
print("Cities  :", df["city"].nunique())
print("Stations:", df["station"].nunique())

States  : 31
Cities  : 266
Stations: 496

In [6]:
df["pollutant_id"].value_counts()

pollutant_id
NO2      487
PM2.5    487
PM10     482
CO       478
SO2      475
OZONE    473
NH3      432
Name: count, dtype: int64

In [7]:
df["state"].value_counts()

state
Maharashtra          563
Uttar_Pradesh        353
Rajasthan            314
Delhi                254
Karnataka            253
Bihar                216
Haryana              199
Madhya Pradesh       171
TamilNadu            140
Odisha               126
Gujarat              107
West_Bengal          105
Chhattisgarh          91
Telangana             82
Andhra_Pradesh        62
Assam                 62
Punjab                51
Kerala                42
Chandigarh            21
Uttarakhand           20
Jharkhand             18
Mizoram                7
Nagaland               7
Puducherry             7
Sikkim                 7
Himachal Pradesh       7
Tripura                7
Arunachal_Pradesh      6
Meghalaya              6
Jammu_and_Kashmir      5
Manipur                5
Name: count, dtype: int64

In [8]:
df[["pollutant_min", "pollutant_max", "pollutant_avg"]].describe()

       pollutant_min  pollutant_max  pollutant_avg
count    3093.000000    3093.000000    3093.000000
mean       38.447462     110.112512      66.345942
std        52.989872     121.596988      82.902002
min         1.000000       1.000000       1.000000
25%         6.000000      21.000000      11.000000
50%        18.000000      69.000000      33.000000
75%        51.000000     140.000000      88.000000
max       360.000000     500.000000     436.000000

In [9]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0